### ISSUE TITLE
Allow control over range/distribution?

### ISSUE THREAD

**Issue by tabatkins** [tc39/proposal-seeded-random#6]
Per @jfbastien, C++ touched *somewhat*, but ineffectively, on letting the user control the range/distribution of random numbers. Lack of good specification means that, while the ordinary generator is consistent between impls, the alternate distributions are not.  Should we allow specifying this?

Like #5, I think this is a valuable addition, but is equally valuable for `Math.random()`. (The number of times I've written a `randInt()` function for myself, or faked a `uniform()` by averaging three `Math.random()` calls...)  Like #5, I'd like to defer this to a separate proposal for upgrading both random functions, unless the committee decides they'd like to broaden this to altering `Math.random()` too.

**Comment by jfbastien** [comment]
[Reference for C++](http://en.cppreference.com/w/cpp/header/random)

Note how distribution (such as [uniform int](http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution)) don't specify much. See [the libc++ implementation](https://github.com/llvm-mirror/libcxx/blob/5b12e3bdb43ac545206501fae955b37cef0c7475/include/algorithm).

Compare:

* Clang result: https://wandbox.org/permlink/HEUKRqDE1XIOL5pk
* GCC result: https://wandbox.org/permlink/5o3rOMQa0wRQgv8o

Note that re-running each compiler gives you the same result, always, but because they have a different STL implementation they don't agree on results because they compute distribution differently.

**Comment by bakkot** [comment]
I'm on board with adding more distributions, but don't think this proposal is the place to do it. The concern with reproducibility across engines is important, but I think that's satisfied by precisely specifying the algorithm used.

**Comment by tabatkins** [comment]
Yeah, I'm gonna go ahead and close this. If we want to add multiple algos & control over distribution, that's a great thing to discuss for a v2; for v1 just matching Math.random()'s distribution is good and simple (and settling on one prng algo).
